apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: ai-logs
data:
  logstash.conf: |
    input {
      tcp {
        port => 5000
        codec => json
      }
    }
    filter {
      mutate {
        add_field => { "@timestamp" => "%{@timestamp}" }
      }
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "dummy-logs"
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: ai-logs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:8.11.0
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: config
              mountPath: /usr/share/logstash/pipeline
      volumes:
        - name: config
          configMap:
            name: logstash-config
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: ai-logs
spec:
  selector:
    app: logstash
  ports:
    - port: 5000